### ISSUE TITLE
add pubkey per app

### ISSUE THREAD

**Issue by bakhshandeh** [abramsymons/muon-schnorr-signer#1]
https://github.com/abramsymons/muon-schnorr-signer/blob/7b26dfa2f5c22941d376ef540bfb224658d8c04d/utils.js#L143

Does it sign all apps with the same Schnorr key? If yes, it is not secure and it would be better to use a separate key for each app, similar to the deployment process on Muon.

**Comment by abramsymons** [comment]
what is the security issue of using the same key for different apps?

**Comment by bakhshandeh** [comment]
> what is the security issue of using the same key for different apps?

1- The risk of using the signatures for one function in another function is higher when there is only one private key for multiple apps.

2- It is not compatible with Muon core. Each app has its own key there

It is not a big risk, but it would be better to run a separate API for each app or use different keys.

**Comment by abramsymons** [comment]
>  it would be better to run a separate API for each app or use different keys

Important and accurate point.
Although having appId as a parameter in the signature prevents such attacks, not using the same key for different apps is another independent security layer against such sorts of attacks.
I will add a note to the README to encourage not using a single server with a single key and API for multiple apps.
